# This is the practice on numpy

here is a useful reference :
http://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html

In [2]:
import numpy as np

# 1. Reverse a vector (first element becomes last)

In [8]:
x = np.arange(50)
#complete here ,to reverse x
x = x[::-1]
x

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

# 2. Create a 2d array with 1 on the border and 0 inside 

In [16]:
x = np.full((10,10), 0)
#complete here ,to make output as following sample 
x= np.pad(x, pad_width=1, mode='constant', constant_values=1)
x

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

# 3. Multiply a 2x2 matrix (a) by a 2x2 matrix(b)  (real matrix product)

In [18]:
a = np.ones((2,2))
b = np.ones((2,2))

                   #complete here ,to make output as following sample 
c = a.dot(b)
c

array([[ 2.,  2.],
       [ 2.,  2.]])

# 4. Create random vector of size 10 and replace the maximum value by 0

In [22]:
Z = np.random.random(10)
print(Z)
Z[Z.argmax()] = 0
#complete here ,to make output as following sample 
print(Z)

[ 0.78220944  0.1583751   0.7820494   0.0665885   0.41212343  0.00637065
  0.71071905  0.89484702  0.7064315   0.41884543]
[ 0.78220944  0.1583751   0.7820494   0.0665885   0.41212343  0.00637065
  0.71071905  0.          0.7064315   0.41884543]


# 5. How to find the closest value (to a given scalar) in an array? 

In [31]:
z = np.arange(10)
v = np.random.uniform(0,10)
print(z)
print(v)                
                  
index = (np.abs(z-v)).argmin()
print(z[index])

[0 1 2 3 4 5 6 7 8 9]
5.704260675589101
6


# 6. Create a 8x8 matrix and fill it with a checkerboard pattern

In [30]:
#complete here ,to make output as following sample 
def build_checkerboard(w, h) :
    re = np.r_[ w*[1,0] ]              # even-numbered rows
    ro = np.r_[ w*[0,1] ]              # odd-numbered rows
    return np.row_stack(h*(re, ro))
    
print(build_checkerboard(8, 8))

[[1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]]


# 7. Normalize a 5x5 random matrix 

In [44]:
Z = np.random.random((5,5))
print(Z)

Z = (Z - np.min(Z)) / (np.max(Z) - np.min(Z))
print(Z)

[[ 0.60312549  0.47099657  0.32937794  0.08617916  0.0084895 ]
 [ 0.33105704  0.29953413  0.10196851  0.00391551  0.57734274]
 [ 0.13811476  0.54882179  0.63720856  0.85200065  0.63995941]
 [ 0.78882754  0.35181667  0.28363069  0.12958375  0.89122315]
 [ 0.64591481  0.74824795  0.70174737  0.80615354  0.16318198]]
[[ 0.67531255  0.52640261  0.36679774  0.09271153  0.00515492]
 [ 0.36869009  0.33316361  0.11050621  0.          0.64625526]
 [ 0.1512432   0.61411201  0.71372434  0.95579606  0.71682455]
 [ 0.88459966  0.39208629  0.31524037  0.14162872  1.        ]
 [ 0.72353632  0.83886626  0.78645988  0.90412614  0.17949408]]


# 8. Extract the integer part of a random array using 5 different methods 

In [46]:
Z = np.random.uniform(0,10,10)

print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[ 9.  0.  7.  6.  3.  8.  8.  7.  4.  5.]
[ 9.  0.  7.  6.  3.  8.  8.  7.  4.  5.]
[ 9.  0.  7.  6.  3.  8.  8.  7.  4.  5.]
[9 0 7 6 3 8 8 7 4 5]
[ 9.  0.  7.  6.  3.  8.  8.  7.  4.  5.]


# 9. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates

In [50]:
Z = np.random.random((10,2))
print(Z)
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)                          #complete here ,to make output as following sample 
T = np.arctan2(Y,X)
o = (R, T)

print(o)

[[ 0.55027061  0.02975261]
 [ 0.12650514  0.59055547]
 [ 0.6717492   0.87254431]
 [ 0.21209332  0.62196988]
 [ 0.1107509   0.9844498 ]
 [ 0.51302804  0.55684907]
 [ 0.32122436  0.9452987 ]
 [ 0.33961998  0.42600089]
 [ 0.40741413  0.4502353 ]
 [ 0.9242024   0.7931522 ]]
(array([ 0.55107437,  0.60395307,  1.10117236,  0.65713782,  0.99065997,
        0.75715168,  0.99838606,  0.54481051,  0.60720516,  1.21788361]), array([ 0.05401645,  1.35977174,  0.9146967 ,  1.24215942,  1.45876706,
        0.82633422,  1.24322586,  0.89774771,  0.83528525,  0.70923642]))


# 10. Tell the difference between view and copy, among b,c,d which is shade copy of a, which is deep copy of a?

In [82]:
#creat a
a = np.array([[1,2,3],[4,5,6]])
# b is another reference object of the array
b = a
#change b
b[0]=0
print("b:")
print(b)
print("a:")
print(a)

# c is the view on piece of a
c = a[:,1]
#change c
c += -1
print("c:")
print (c)
print("a:")
print(a)

# d is a copy of a
d = a.copy()
d -=d
print("d:")
print(d)
print("a:")
print(a)


b:
[[0 0 0]
 [4 5 6]]
a:
[[0 0 0]
 [4 5 6]]
c:
[-1  4]
a:
[[ 0 -1  0]
 [ 4  4  6]]
d:
[[0 0 0]
 [0 0 0]]
a:
[[ 0 -1  0]
 [ 4  4  6]]


Solutions: d is a shallow copy of a. 